global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']

  - job_name: 'echo_server'
    static_configs:
      - targets: ['server:1233']