services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

  postgrest:
    image: postgrest/postgrest:latest
    environment:
      PGRST_DB_URI: "postgres://postgres:postgres@db:5432/mydb"
      PGRST_DB_SCHEMA: "public"
      PGRST_DB_ANON_ROLE: "postgres"
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data: